name: HydroMind
options:
  bundleIdPrefix: com.sebastiandoyle
  deploymentTarget:
    iOS: "16.0"
targets:
  HydroMind:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - project.yml
          - "*.xcodeproj"
          - build
          - fastlane
          - "*.json"
          - "*.plist"
          - raw_screenshots
          - "*.txt"
          - "*.md"
          - HydroMindTests
    resources:
      - path: Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sebastiandoyle.hydromind
        PRODUCT_NAME: HydroMind
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: 7277AB8379
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SUPPORTED_DESTINATIONS: "iPhone, iPad"
        SWIFT_VERSION: "5.9"
  HydroMindTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: HydroMindTests
    dependencies:
      - target: HydroMind
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sebastiandoyle.hydromind.tests
        DEVELOPMENT_TEAM: 7277AB8379
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: YES
