app_identifier "com.sebastiandoyle.hydromind"
username "sebastian.doyle@outlook.com"
skip_metadata true
skip_binary_upload true
overwrite_screenshots true
force true
precheck_include_in_app_purchases false
